# Generated by Django 5.0.14 on 2025-12-18 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_docteur_options_alter_patient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_alrg', models.CharField(max_length=50, verbose_name="Nom de l'allergie")),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mal', models.CharField(max_length=50, verbose_name='Nom de la maladie')),
            ],
        ),
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_orga', models.CharField(max_length=100, verbose_name="Nom de l'organisme")),
                ('type_orga', models.CharField(max_length=50, verbose_name="Type d'organisme")),
                ('taux_remise', models.DecimalField(decimal_places=2, help_text='Pourcentage de couverture (ex: 80.00)', max_digits=5, verbose_name='Taux de remise (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vac', models.CharField(max_length=50, verbose_name='Nom du vaccin')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentAllergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensite', models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Grave', 'Grave')], default='Faible', max_length=20, verbose_name='Intensité')),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('allergie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.allergie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents_allergies', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Antécédent Allergie',
            },
        ),
        migrations.CreateModel(
            name='AntecedentMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnostic', models.DateField(blank=True, null=True, verbose_name='Date du diagnostic')),
                ('est_chronique', models.BooleanField(default=False, verbose_name='Maladie Chronique')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents_maladies', to='accounts.patient')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.maladie')),
            ],
            options={
                'verbose_name': 'Antécédent Maladie',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_injection', models.DateField(verbose_name="Date de l'injection")),
                ('observation', models.TextField(blank=True, verbose_name='Observations')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='accounts.patient')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.vaccin')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
            },
        ),
    ]
