# Generated by Django 5.0.14 on 2025-12-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docteur',
            options={'verbose_name': 'Médecin', 'verbose_name_plural': 'Médecins'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Dossier Administratif Patient', 'verbose_name_plural': 'Dossiers Patients'},
        ),
    ]
