# Generated by Django 5.0.14 on 2025-12-18 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_docteur_options_alter_patient_options'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mutuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affilies', to='dossiers.mutuelle', verbose_name='Organisme de Mutuelle'),
        ),
    ]
