# Generated by Django 5.0.14 on 2026-01-05 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_patient_mutuelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du RDV')),
                ('heure', models.TimeField(verbose_name='Heure du RDV')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif de consultation')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs_assures', to='accounts.docteur', verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs_pris', to='accounts.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.AddConstraint(
            model_name='rdv',
            constraint=models.UniqueConstraint(fields=('docteur', 'date', 'heure'), name='unique_rdv_creneau_docteur'),
        ),
    ]
