# Generated by Django 5.0.14 on 2026-01-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdv',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='rdv',
            name='unique_rdv_creneau_docteur',
        ),
    ]
