# Generated by Django 5.0.14 on 2026-01-10 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0002_alter_rdv_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'acte")),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(auto_now_add=True, verbose_name='Date de consultation')),
                ('diagnostic', models.TextField(verbose_name='Diagnostic')),
                ('commentaires', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('est_revision', models.BooleanField(default=False, verbose_name='Est une révision')),
                ('actes', models.ManyToManyField(related_name='consultations', to='consultations.acte', verbose_name='Actes réalisés')),
                ('consultation_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='consultations.consultation', verbose_name="Consultation d'origine (si révision)")),
                ('rdv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='planning.rdv', verbose_name='Rendez-vous associé')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordonnance', models.DateField(auto_now_add=True, verbose_name="Date de l'ordonnance")),
                ('traitement', models.TextField(help_text='Détaillez les médicaments prescrits ici.', verbose_name='Traitement (Médicaments et posologie)')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='consultations.consultation')),
            ],
        ),
    ]
