# Generated by Django 5.0.14 on 2026-01-10 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField(auto_now_add=True, verbose_name='Date de facturation')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour calculer automatiquement selon les actes.', max_digits=10, null=True, verbose_name='Montant Total (DH)')),
                ('statut_paiement', models.CharField(choices=[('NON_PAYE', 'Non payée'), ('PAYE', 'Payée'), ('EN_ATTENTE', 'En attente')], default='NON_PAYE', max_length=20, verbose_name='Statut du paiement')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='consultations.consultation', verbose_name='Consultation associée')),
            ],
        ),
    ]
